# Generated by Django 5.2 on 2025-04-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villa", "0003_alter_rent_user_alter_villa_user_remove_rent_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="villa",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
