# Generated by Django 5.1.7 on 2025-04-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparteman', '0003_alter_rent_user_alter_place_user_alter_place_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('available', 'موجود'), ('rented', 'اجاره داده شده')], default='available', max_length=10),
        ),
    ]
