# Generated by Django 5.1.7 on 2025-04-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparteman', '0004_place_image_place_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.CharField(default='Tehran', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='aparteman'),
        ),
    ]
